version: '3.2'

services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    hostname: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper
    hostname: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  ch-11:
    image: yandex/clickhouse-server
    hostname: ch-11
    volumes: 
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./config/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./config/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./config/macros_11.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8011:8123
      - 9011:9000
    depends_on: 
      - zoo1
      - zoo2
      - zoo3
  
  ch-12:
    image: yandex/clickhouse-server
    hostname: ch-12
    volumes: 
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./config/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./config/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./config/macros_12.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8012:8123
      - 9012:9000
    depends_on: 
      - zoo1
      - zoo2
      - zoo3

  ch-21:
    image: yandex/clickhouse-server
    hostname: ch-21
    volumes: 
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./config/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./config/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./config/macros_21.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8021:8123
      - 9021:9000
    depends_on: 
      - zoo1
      - zoo2
      - zoo3

  ch-22:
    image: yandex/clickhouse-server
    hostname: ch-22
    volumes: 
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./config/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
      - ./config/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
      - ./config/macros_22.xml:/etc/clickhouse-server/config.d/macros.xml
    ports:
      - 8022:8123
      - 9022:9000
    depends_on: 
      - zoo1
      - zoo2
      - zoo3

  chproxy:
    image: chproxy
    hostname: chproxy
    volumes: 
      - ./config/chproxy.yaml:/chproxy.yaml
    command: ["-config=/chproxy.yaml"]
    ports:
      - 9090:9090
    depends_on: 
      - ch-11
      - ch-12
      - ch-21
      - ch-22     